* Original task
Task:
#+begin_quote
El objetivo de este ejercicio es programar con javascript un
"ecommerce".

render_list_of_items: es una función que se ejecuta al abrir la pagina
en el navegador. Tiene que generar el html con el listado de productos
de la tienda, detallados en la variable "data". La propiedad 'img' se
correponde con el nombre de las imagenes .jpg de la carpeta
img. Puedes utilizar cualquier recurso de CSS, por ejemplo bootstrap o
materialize, para generar algun tipo de ficha/card de producto, con su
nombre y su precio.

addItem: esta función tiene que ejecutarse para añadir un producto al
carrito de la compra. Cada ficha de producto debe tener un botón para
añadir el producto a la cesta. También cada producto debe tener un
indicador de la cantidad de producto contenida en la cesta.

removeItem: Lo mismo que addItem pero para quitar producto de la
cesta.

Es importante que haya en algún lugar de la página el número total de
items en la cesta así como el precio total de la compra, que deben
actualizarse debidamente al poner y quitar productos de la cesta.

Bonus points: Adicionalmente, puedes incorporar otras funcionalidades
que consideres interesantes, p.ej.  - Algún tipo de visualización del
contenido de la cesta.  - Listado/menú/cesta adaptable a móbil.  -
Persistencia del carrito en localStorage.  - Uso de WebComponents - o
cualquier otra cosa que te parezca interesante !
#+end_quote

* First implementation

* After the first implementation: using web components
We can turn the items in the grid and the basket into components. We
will turn them into ``custom elements''

* A futher step: data flow

Now: [...]

What we want: [...]

